name: luid
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.4.0 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.6
  get: 4.6.6
  styled_widget: ^0.4.1
  flutter: 
    sdk: flutter
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  flutter_localization: ^0.2.1
  flutter_easyloading: ^3.0.5
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.1
  mobile_scanner: ^5.1.1
  image_picker: ^1.1.2
  qr_flutter:
      git:
        url: https://github.com/theyakka/qr.flutter.git
dev_dependencies: 
  flutter_lints: 4.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/home/
    - assets/logo.png
